"""Add summarized

Revision ID: 7f21b142345b
Revises: 246a5cb1818a
Create Date: 2025-12-27 22:14:10.950227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f21b142345b'
down_revision: Union[str, Sequence[str], None] = '246a5cb1818a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('news_articles', sa.Column('summarized', sa.Boolean(), nullable=True))
    op.drop_column('news_articles', 'Summarized')
    op.execute('UPDATE news_articles SET summarized = FALSE WHERE summarized IS NULL')
    op.alter_column('news_articles', 'summarized', nullable=False)
    op.alter_column('news_articles', 'summarized', server_default=sa.text('FALSE'))
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('Summarized', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('news_articles', 'summarized')
    # ### end Alembic commands ###
