"""Add sumarized

Revision ID: 9e6076da2c4b
Revises: b540bdef0f65
Create Date: 2025-12-27 22:00:48.717988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6076da2c4b'
down_revision: Union[str, Sequence[str], None] = 'b540bdef0f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('Summarized', sa.Boolean(), nullable=True))
    op.execute('UPDATE news_articles SET Summarized = FALSE WHERE Summarized IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_articles', 'Summarized')
    # ### end Alembic commands ###
