"""scrapping schema

Revision ID: e0816d23b1aa
Revises: 2481f13e42ad
Create Date: 2025-12-23 20:44:02.560170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0816d23b1aa'
down_revision: Union[str, Sequence[str], None] = '2481f13e42ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('scraping_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_articles', 'scraping_status')
    # ### end Alembic commands ###
